### ISSUE TITLE
Summoner always not found

### ISSUE THREAD

**Issue by ghost** [Aztorius/legendsreplay#4]
I try our application but always username not found

**Comment by Aztorius** [comment]
Where ? Can you paste here the content of 'Status' tab ?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/30040788/40997896-703e16e6-6906-11e8-9f9d-0ae945986994.png)

**Comment by Aztorius** [comment]
It works on my network. It seems like an issue on your network.
Try to open [https://legendsreplay.000webhostapp.com/](https://legendsreplay.000webhostapp.com/) on your web-browser. It should print "Legends Replay".

**Comment by ghost** [comment]
Yes https://legendsreplay.000webhostapp.com/ response : Legends Replay

**Comment by Aztorius** [comment]
Well that's strange. Check your firewall and your anti-virus software. That's most likely a firewall issue.

**Comment by ben-r-smith** [comment]
I'm having this issue as well. I've given LegendsReplay access to the firewall, but that doesn't seem to resolve. When I open the replay server  in a browser I see the following
> Website is archived.
> If you are owner this site, please login to your admin panel to re-activate the project.

I also see this error
> 17:40:33 | [ERROR] Status of EUN1: Connection timed out
